language: node_js
install: npm install
node_js:
  - 'node'
  - '6'
addons:
  code_climate:
    repo_token: 8d9cf117d83e6088b5efbd56cd9ef1adb7374200097702e3db4396ef727cefd6
notifications:
  email: false
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
